CREATE TABLE similarities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   event_id_a BIGINT,
   event_id_b BIGINT,
   score DOUBLE PRECISION,
   timestamp TIMESTAMP with time zone,
   CONSTRAINT pk_similarities PRIMARY KEY (id)
);

CREATE TABLE actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT,
   event_id BIGINT,
   score DOUBLE PRECISION,
   last_interaction TIMESTAMP with time zone,
   CONSTRAINT pk_actions PRIMARY KEY (id)
);