create TABLE IF NOT EXISTS user_action (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user_id BIGINT NOT NULL,
	event_id BIGINT NOT NULL,
	action_type VARCHAR(20) NOT NULL,
	created TIMESTAMP NOT NULL,
	weight DOUBLE PRECISION,
	CONSTRAINT pk_user_action PRIMARY KEY (id),
	CONSTRAINT unique_user_action_user_id_event_id UNIQUE (user_id, event_id)
);

create TABLE IF NOT EXISTS event_similarity (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	aevent_id BIGINT NOT NULL,
	bevent_id BIGINT NOT NULL,
	score DOUBLE PRECISION,
	CONSTRAINT pk_event_similarity PRIMARY KEY (id),
	CONSTRAINT unique_event_similarity_aevent_id_bevent_id UNIQUE (aevent_id, bevent_id)
);