#server:
#  port: 0
#
#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations:
#            - classpath:config/core/{application}
#            - classpath:config/infra/{application}
#            - classpath:config/stats/{application}
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    hostname: localhost
#    instance-id: "${spring.application.name}:${server.port}"
#    leaseRenewalIntervalInSeconds: 10
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/core/{application}
            - classpath:config/infra/{application}
            - classpath:config/stats/{application}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 10
server:
  port: 0