server:
  port: 9091

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      uri: http://localhost:9091
      server:
        native:
          searchLocations:
            - 'classpath:/config/core/'
            - 'classpath:/config/infra/'
            - 'classpath:config/stats/'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true