spring:
  application:
    name: stats-server
  config:
    import: optional:configserver:http://config-server:9091
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewm-stats
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 10
server:
  port: 9090