spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://user-db:5432/ewm-user
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  sql:
    init:
      mode: always