#server:
#  port: 8085
#
#spring:
#  application:
#    name: request-service
#  config:
#    import: "configserver:"
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: config-server
#      fail-fast: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    hostname: localhost
#    instanceId: "${spring.application.name}:${server.port}"
#    leaseRenewalIntervalInSeconds: 10
spring:
  application:
    name: request-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
server:
  port: 0