spring:
  application:
    name: event-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
       enabled: true
       service-id: config-server
      fail-fast: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${server.port}"
    leaseRenewalIntervalInSeconds: 10