spring:
  application:
    name: collector
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 10000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true