spring:
  cloud:
    gateway:
      routes:
        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - RewritePath=/admin/users/(?<segment>.*), /api/$\{segment}

        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: request-service_route
          uri: lb://request-service
          predicates:
            - Path=/requests/**

server:
  port: 8080