spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: event_service_category_route
          uri: lb://event-service
          predicates:
           - Path=/admin/categories/**, /categories/**

        - id: event_service_compilation_route
          uri: lb://event-service
          predicates:
           - Path=/compilations/**, /admin/compilations/**

        - id: event-service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /users/{userId}/events, /users/{userId}/events/{eventId}, /events/**

        - id: event_service_route_add_param
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events
            - Query=from
            - Query=size

        - id: request-service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests, /users/{userId}/requests/**, /requests/**